// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "./Preset";

/**
 * Sesión activa de procesamiento. Se persiste a disco en cada
 * `file_done` para permitir reanudar tras cierre o cancelación.
 */
export type ActiveBatch = { started_at: string, preset: Preset, files: Array<string>, completed: Array<string>, failed: Array<string>, };
