// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resultado del modelo de estética (NIMA-style):
 * `mean` en 1..10 y `std_dev` como dispersión de la distribución.
 */
export type AestheticScore = { mean: number, std_dev: number, };
