// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisFileError } from "./AnalysisFileError";

export type AnalysisDoneEvent = { total: number, analizadas: number, desde_cache: number, cancelado: boolean, errores: Array<AnalysisFileError>, };
