// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileError } from "./FileError";

export type BatchDoneEvent = { total: number, exitosas: number, fallidas: number, cancelado: boolean, errores: Array<FileError>, };
