// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Decisión del usuario sobre conservar o descartar una foto.
 */
export type CullStatus = "Keep" | "Reject" | "Undecided";
