// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DedupConfig = { 
/**
 * Distancia de Hamming máxima entre `perceptual_hash` para
 * considerar dos fotos como repetidas.
 */
hamming_threshold: number, 
/**
 * Separación temporal máxima en segundos. Solo se aplica si
 * ambas fotos tienen `capture_time`.
 */
time_window_seconds: number, };
