// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resumen de la detección de caras.
 */
export type FaceSummary = { count: number, largest_face_frac: number, main_face_centered: number, };
