// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Estado de ffmpeg: ruta detectada (si la hay) y por tanto si el
 * procesamiento de video está disponible.
 */
export type FfmpegStatus = { available: boolean, path: string | null, };
