// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageAdjustments = { 
/**
 * Brillo. -1 = oscurece a negro, +1 = aclara a blanco.
 */
brightness: number, 
/**
 * Contraste. -1 = aplana a gris medio, +1 = duplica el contraste.
 */
contrast: number, 
/**
 * Saturación. -1 = blanco y negro, +1 = duplica la saturación.
 */
saturation: number, 
/**
 * Temperatura. -1 = más frío (azul), +1 = más cálido (naranja/rojo).
 */
temperature: number, };
