// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogoBackground } from "./LogoBackground";
import type { LogoPosition } from "./LogoPosition";

export type LogoConfig = { 
/**
 * Referencia al logo dentro de la biblioteca de la app.
 */
logo_id: string, position: LogoPosition, 
/**
 * Ancho del logo como % del ancho de la imagen base.
 */
scale_pct: number, 
/**
 * Opacidad global del logo (0.0–1.0).
 */
opacity: number, background: LogoBackground | null, };
