// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metrics = { enabled: boolean, images_processed: number, videos_processed: number, files_failed: number, batches_completed: number, batches_cancelled: number, analyses_completed: number, rejects_moved: number, recommendations_exported: number, first_seen_unix: number, };
