// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisFileError } from "./AnalysisFileError";

export type MoveRejectsReport = { 
/**
 * Cuántos registros tenían `status == Reject` cuando se invocó
 * el comando. Si es 0, no había nada que mover.
 */
considerados: number, movidos: string[], errores: Array<AnalysisFileError>, };
