// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recorte adicional aplicado al output principal. Cada `NetworkCrop`
 * produce un archivo extra `<nombre>__<id>.<ext>` con la imagen
 * centrada-y-recortada al aspect ratio (width/height) y reescalada a
 * esas dimensiones exactas.
 *
 * Útil para entregar una foto en varios formatos de redes sociales
 * en una sola pasada de procesamiento.
 */
export type NetworkCrop = { 
/**
 * Sufijo que aparece en el nombre del archivo.
 */
id: string, 
/**
 * Etiqueta legible para la UI.
 */
label: string, width: number, height: number, };
