// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkOrientation } from "./NetworkOrientation";

/**
 * Especificación de una red social. `aspect_ratio` es ancho/alto.
 */
export type NetworkSpec = { id: string, name: string, aspect_ratio: number, orientation: NetworkOrientation, suggested_width: number, suggested_height: number, };
