// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputFormat } from "./OutputFormat";

export type PreviewResult = { base64: string, width: number, height: number, format: OutputFormat, };
