// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Métricas objetivas de calidad calculadas sobre la luminancia.
 */
export type QualityMetrics = { sharpness_raw: number, clipped_highlights_pct: number, clipped_shadows_pct: number, mean_luma: number, contrast: number, };
