// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Recommendation = { path: string, composite_score: number, fit: number, recommendation: number, };
