// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResizeMode } from "./ResizeMode";

export type ResizeConfig = { mode: ResizeMode, width: number | null, height: number | null, percentage: number | null, keep_aspect_ratio: boolean, allow_upscale: boolean, };
