// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pesos editables del puntaje compuesto. Los pesos de la base
 * (sharpness, exposure, aesthetic, resolution) deberían sumar 1.0,
 * pero el código tolera otros valores y siempre recorta el
 * resultado a [0, 1].
 */
export type ScoringWeights = { w_sharpness: number, w_exposure: number, w_aesthetic: number, w_resolution: number, face_bonus_max: number, };
