// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sub-puntajes normalizados a 0..1 que componen el puntaje final.
 */
export type SubScores = { sharpness: number, exposure: number, resolution: number, aesthetic: number, face_bonus: number, };
