// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Avance dentro de un video puntual mientras ffmpeg lo procesa.
 */
export type VideoProgressEvent = { ruta: string, 
/**
 * Microsegundos procesados del video.
 */
current_us: number, 
/**
 * Duración total en microsegundos (0 si no se pudo determinar).
 */
total_us: number, };
