// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Posición del CENTRO del logo en coordenadas normalizadas 0.0–1.0
 * respecto a la imagen base.
 */
export type LogoPosition = { x: number, y: number, };
