// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recuadro opcional dibujado detrás del logo.
 *
 * El canal alfa de `color_rgba` controla la translucidez del fondo;
 * `padding_pct` es el relleno alrededor del logo, expresado como %
 * del ancho del logo ya reescalado.
 */
export type LogoBackground = { color_rgba: [number, number, number, number], padding_pct: number, };
