// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputFormat } from "./OutputFormat";

export type OutputConfig = { format: OutputFormat, quality: number, folder: string, filename_pattern: string, preserve_structure: boolean, };
