// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageAdjustments } from "./ImageAdjustments";
import type { LogoConfig } from "./LogoConfig";
import type { NetworkCrop } from "./NetworkCrop";
import type { OutputConfig } from "./OutputConfig";
import type { ResizeConfig } from "./ResizeConfig";
import type { TextWatermark } from "./TextWatermark";

export type Preset = { name: string, resize: ResizeConfig, 
/**
 * **Legacy.** Antes de v0.2 había un solo logo por preset.
 * Se conserva por compatibilidad de lectura: los presets viejos
 * guardados como `{ "logo": {...} }` siguen cargando. Al guardar
 * se vuelca al primer slot de `logos` y este campo queda `None`.
 * Para presets nuevos usar `logos` directamente.
 */
logo: LogoConfig | null, 
/**
 * Lista de marcas de agua compuestas en orden (firma + sello +
 * frame, etc.). Si `logo` está set por compatibilidad, se trata
 * como si fuera el primer elemento de esta lista.
 */
logos: Array<LogoConfig>, output: OutputConfig, 
/**
 * Recortes adicionales (uno por red/formato). Se generan después
 * del output principal usando la imagen ya redimensionada + con
 * marca de agua. Vacío = solo se produce el output principal.
 */
network_crops: Array<NetworkCrop>, 
/**
 * Marcas de agua por TEXTO. Se componen DESPUÉS de los logos
 * para que el texto quede por encima de las marcas gráficas.
 */
text_watermarks: Array<TextWatermark>, 
/**
 * Ajustes de exposición / contraste / saturación / temperatura
 * aplicados ANTES de las marcas de agua. Por defecto es
 * identidad (no-op).
 */
adjustments: ImageAdjustments, };
