// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogoBackground } from "./LogoBackground";
import type { LogoPosition } from "./LogoPosition";

/**
 * Marca de agua por TEXTO (firma del fotógrafo, fecha, etc.).
 *
 * El tamaño es relativo al ancho de la imagen base
 * (`font_size_pct`), igual que el logo, para que el mismo preset
 * se vea proporcional en fotos de distintas resoluciones. Soporta
 * los tokens `{filename}` y `{date}` en el campo `text`.
 */
export type TextWatermark = { 
/**
 * Contenido. Acepta tokens `{filename}` y `{date}`.
 */
text: string, 
/**
 * Tamaño de fuente como fracción del ancho de la imagen base
 * (típicamente 0.02–0.08).
 */
font_size_pct: number, color_rgba: [number, number, number, number], position: LogoPosition, opacity: number, background: LogoBackground | null, };
